name: Deploy to staging or prod and test
concurrency: staging_environment
on:
  push:
    branches: [ main ]
env:
  fastly_vcl_service_id: eLht3G2V1XIpkzW8RQmZb0
  fastly_compute_service_id: 9joTR7C2DIWAzpwW1rCZ86
  domain: staging-unpkg.jakechampion.name
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
      - name: 'Install dependencies'
        run: npm ci
      - name: Set cache-key
        id: cache-key
        run: echo "CACHE_KEY=compute-package-$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - name: Restore compute-package from cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # pin@v3
        id: compute-package
        with:
          path: pkg/package.tar.gz
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
      - if: steps.compute-package.outputs.cache-hit != 'true'
        name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@c2f38daa58a1a6562575c9665f13b080803b8989 # pin@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cli_version: '10.5.0'
      - if: steps.compute-package.outputs.cache-hit != 'true'
        run: fastly compute build --package-name package
      - uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # pin@v3
        with:
          name: ${{ steps.cache-key.outputs.CACHE_KEY }}
          path: pkg/package.tar.gz
      - uses: ./.github/actions/terraform
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_working_dir: fastly/terraform/staging
          fastly-api-token: ${{ secrets.FASTLY_API_KEY }}
          fastly_vcl_service_id: ${{ env.fastly_vcl_service_id }}
          fastly_compute_service_id: ${{ env.fastly_compute_service_id }}

  end-to-end-test:
    needs: [ deploy-to-staging ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # pin@v4.0.0
        with:
          node-version: 18.x
      - name: 'Install test dependencies'
        run: npm ci
        working-directory: "./test"
      - run: npm run test:integration
        working-directory: "./test"
        env:
          HOST: "https://${{ env.domain }}"
